### ISSUE TITLE
Readings Overwrite Logic

### ISSUE THREAD

**Issue by GorAlexander** [LevchenCoM/meters#1]
Hi @LevchenCoM, 
Could you please implement the readings overwrite logic as stated in the task (pt. 2b-1):

> Each new upload of readings for the period [A, B] should overwrite existing meter’s records for the period [A, B] - i.e. records uploaded earlier.

Also, the logic should not rely on records order in the input file.
Here're some [more csv readings files](https://drive.google.com/drive/u/2/folders/1xRGg7u0hUUJfCV7DA7cPWbXR3JFVWLQt) to work with.

Please, ask if any questions.

**Comment by mklevk** [comment]
I changed readings overwrite logic based on your wishes.

Now when user try to upload new readings from .csv file, server first will check if record with same date exist in DataBase and then:
1. If record with the same date exist in DB - update it;
2. Else - will create new record obj

After this things, server will perform consumptions recalculating using class method "consumptions_recalculation()" of Meters model.

Tests for this logic was added to meters/tests/

Waiting for feedback.
