### ISSUE TITLE
Readings Import Performance

### ISSUE THREAD

**Issue by GorAlexander** [LevchenCoM/meters#3]
Hi @LevchenCoM,

The latest version is almost a working solution. However, we'll have one more major change-request.

We have found the poor performance of readings import. This may be critical when working with a huge amount of data (~10 years time span) or when applying this approach to high-frequency readings (5-minute, half-hourly resolution).

Currently, loading one reading produces DB queries:
1. SELECT - try to get the record by date (if one exists)
2. INSERT - create the record (see the for-loop of [meter_page](https://github.com/LevchenCoM/meters/blob/master/django_meters/meters/views.py) view)
3. A number of UPDATES in [Meters.consumptions_recalculation](https://github.com/LevchenCoM/meters/blob/master/django_meters/meters/models.py)

So, the number of queries (at least pts. 1, 2) has a linear dependency [O(n)](https://en.wikipedia.org/wiki/Time_complexity) on the number of readings being imported. Can we make this relation constant O(1) - i.e. the fixed number of queries with no dependency on how many readings we import?

Additionally, you are free to look for any other techniques for improving performance.

**Comment by mklevk** [comment]
Hi @GorAlexander,

When I developed this logic, I thought about this problem... Could i have a call with you? I need a little advice

**Comment by mklevk** [comment]
Done.

I commited changes in readings import functionality. Please check it!
I tried as much as possible reduce the number of queries to the database.

P.S
Don't forget to install all dependencies from Pipfile.lock. 

Thanks!

**Comment by GorAlexander** [comment]
Good, thanks!
