### ISSUE TITLE
Lost Consumption Value

### ISSUE THREAD

**Issue by GorAlexander** [LevchenCoM/meters#4]
Hi @LevchenCoM,

This is the minor change-request to fix the bug we've found in the latest version.

**Case description.**
When loading files from our [CSV test suite](https://drive.google.com/drive/u/2/folders/1xRGg7u0hUUJfCV7DA7cPWbXR3JFVWLQt) one-by-one (test_1.csv, then 2nd, then 3rd), it turns out that the reading for 2018-05-31 gets a zero consumption value, where the expected value is 10.

Can we fix this case and cover it with a unit test? 
We suggest that the test executes a complete logic of readings import rather than making direct DB inserts followed by recalcultate method call. You can use the following approach to the test:

- Implement readings import logic outside of the view, e.g. as a function 'import_readings'
- The unit test calls: 
`import_readings(meter, [readings set A])`
`import_readings(meter, [readings set B])`
`...`
`assertions ...`

Please, take as much time you need for the today's issues. No need in rush.
Thanks!

**Comment by mklevk** [comment]
Hi. Bug fixed
